#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorAlpha,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBeta,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorGamma,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorDelta,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{

	while(true)
	{
getJoystickSettings(joystick);

		if(joy2Btn(1) == 1)
		{
			motor[motorBeta] = 50;
			wait1Msec(100);
			motor[motorBeta] = 0;
		}

		if(joy2Btn(4) == 1)
		{
			motor[motorBeta] = -50;
			wait1Msec(100);
			motor[motorBeta] = 0;
    }

    if(joy2Btn(3) == 1)
    {
			motor[motorAlpha] = 50;
		  wait1Msec(100);
			motor[motorAlpha] = 0;
		}

		if(joy2Btn(2) == 1)
		{
			motor[motorAlpha] = -50;
			wait1Msec(100);
			motor[motorAlpha] = 0;
	  }
    if(10 < joystick.joy1_y1 < -10)
    {
		motor[motorGamma] = joystick.joy1_y1;
	  }

	  if(10 < joystick.joy1_y2 < -10)
	  {
		motor[motorDelta] = -joystick.joy1_y2;
    }
}
}
